// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69tw1Jta1HD50F__fIoxMvHRzv_MOTmU',
    appId: '1:707204306778:web:6ee88d10fd6c2e0d534563',
    messagingSenderId: '707204306778',
    projectId: 'sbas-4c928',
    authDomain: 'sbas-4c928.firebaseapp.com',
    storageBucket: 'sbas-4c928.appspot.com',
    measurementId: 'G-51MFEGX041',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNyWnVzB1Hi19QXvgQ9dPZ6mhlGCXRhE',
    appId: '1:707204306778:android:6762d9e9ce793101534563',
    messagingSenderId: '707204306778',
    projectId: 'sbas-4c928',
    storageBucket: 'sbas-4c928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5fhMYe7hBOhGlo6YcpSaYL9--FJR1UQY',
    appId: '1:707204306778:ios:0c6645a9ff684baa534563',
    messagingSenderId: '707204306778',
    projectId: 'sbas-4c928',
    storageBucket: 'sbas-4c928.appspot.com',
    iosClientId: '707204306778-7siio03q1m1g78beu8aek2aotrn19fp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5fhMYe7hBOhGlo6YcpSaYL9--FJR1UQY',
    appId: '1:707204306778:ios:0c6645a9ff684baa534563',
    messagingSenderId: '707204306778',
    projectId: 'sbas-4c928',
    storageBucket: 'sbas-4c928.appspot.com',
    iosClientId: '707204306778-7siio03q1m1g78beu8aek2aotrn19fp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbas',
  );
}
