name: SBAS

on:
  push:
    branches: [ 'dev' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12'
          
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.7.10
        channel: stable

    - run: flutter --version
      
    - name: Install packages
      run: flutter pub get
      
    - name: Build
      run: flutter build apk --release --split-per-abi --sound-null-safety
