name: SBAS

on:
  push:
    branches: [ 'dev' ]
  pull_request:
    branches: [ 'dev' ]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12'
        
    - name: Install jq
      run: sudo apt-get install -y jq
          
    - uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: 3.7.11
        channel: stable

    - run: flutter --version
      
    - name: Install packages
      run: flutter pub get
      
    - name: Build
      run: |
        flutter build apk --release --split-per-abi --sound-null-safety
        mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/sbas.apk
      
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        local: build/app/outputs/flutter-apk/sbas.apk
        remote_path: ${{ secrets.PATH }}

  iOS:
    runs-on: macos-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: 3.7.11
        channel: stable

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS Archive
      run: flutter build ios --release --no-codesign
